add tests

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -20,9 +20,6 @@ jobs:
       POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
       POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
       POSTGRES_PORT: 5432
-      AFRICASTALKING_API_KEY: ${{secrets.AFRICASTALKING_API_KEY}}
-      AFRICASTALKING_USERNAME: ${{ secrets.AFRICASTALKING_USERNAME }},
-      AFRICASTALKING_SENDER_ID: ${{ secrets.AFRICASTALKING_SENDER_ID }}
 
     services:
       database:
@@ -62,12 +59,13 @@ jobs:
         DATABASE_PASSWORD: postgres
         DATABASE_HOST: localhost
         DATABASE_PORT: 5432
+        AFRICASTALKING_API_KEY: ${{secrets.AFRICASTALKING_API_KEY}}
+        AFRICASTALKING_USERNAME: ${{ secrets.AFRICASTALKING_USERNAME }}
+        AFRICASTALKING_SENDER_ID: ${{ secrets.AFRICASTALKING_SENDER_ID }}
 
 
       run: |
-        echo "AFRICASTALKING_API_KEY=${{secrets.AFRICASTALKING_API_KEY}}" >> $GITHUB_ENV
-        echo "AFRICASTALKING_USERNAME=${{secrets.AFRICASTALKING_USERNAME}}" >> $GITHUB_ENV
-        echo "AFRICASTALKING_SENDER_ID=${{secrets.AFRICASTALKING_SENDER_ID}}" >> $GITHUB_ENV
+        echo $env
         pip install pytest pytest-django pytest-cov 
         export DJANGO_SETTINGS_MODULE=commerce.settings
         python manage.py makemigrations
@@ -77,103 +75,103 @@ jobs:
 
 
 
-  setup-infrastructure:
-    name: Set Up Infrastructure
-    runs-on: ubuntu-latest
-    if: ${{github.event_name == 'push'}}
-    defaults:
-      run:
-        shell: bash
-        working-directory: ./infrastructure
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: configure aws credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-to-assume: ${{ secrets.AWS_ROLE }}
-          aws-region: ${{ vars.AWS_REGION }}
-          role-session-name: GitHub-OIDC-TERRAFORM
-
-
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.3.0
-
-      - name: Terraform fmt
-        id: fmt
-        run: terraform fmt -check
-        continue-on-error: true
-
-      - name: Terraform Init
-        id: init
-        run: terraform init
-
-      - name: Terraform Validate
-        id: validate
-        uses: hashicorp/terraform-github-actions/validate@v0.3.7
-
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan -no-color
-        if: github.event_name == 'pull_request'
-        continue-on-error: true
-
-      - uses: actions/github-script@v6
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            <details><summary>Validation Output</summary>
-        
-            \`\`\`\n
-            ${{ steps.validate.outputs.stdout }}
-            \`\`\`
-            
-            </details>
-            
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            
-            <details><summary>Show Plan</summary>
-            
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-            
-            </details>
-            
-            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-            
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false
-        env:
-          TF_VAR_DJANGO_SECRET_KEY:  ${{ secrets.DJANGO_SECRET_KEY }}
-          TF_VAR_DEBUG:  ${{ vars.DEBUG_MODE }}
-          TF_VAR_DATABASE_NAME: ${{secrets.POSTGRES_DB}}
-          TF_VAR_DATABASE_USER: ${{secrets.POSTGRES_USER}}
-          TF_VAR_DATABASE_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
-          TF_VAR_AFRICASTALKING_API_KEY:  ${{ secrets.AFRICASTALKING_API_KEY }}
-          TF_VAR_AFRICASTALKING_USERNAME:  ${{ secrets.AFRICASTALKING_USERNAME }}
-          TF_VAR_AFRICASTALKING_SENDER:  ${{ secrets.AFRICASTALKING_SENDER_ID }}
+#  setup-infrastructure:
+#    name: Set Up Infrastructure
+#    runs-on: ubuntu-latest
+#    if: ${{github.event_name == 'push'}}
+#    defaults:
+#      run:
+#        shell: bash
+#        working-directory: ./infrastructure
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v2
+#
+#      - name: configure aws credentials
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          role-to-assume: ${{ secrets.AWS_ROLE }}
+#          aws-region: ${{ vars.AWS_REGION }}
+#          role-session-name: GitHub-OIDC-TERRAFORM
+#
+#
+#      - name: Setup Terraform
+#        uses: hashicorp/setup-terraform@v2
+#        with:
+#          terraform_version: 1.3.0
+#
+#      - name: Terraform fmt
+#        id: fmt
+#        run: terraform fmt -check
+#        continue-on-error: true
+#
+#      - name: Terraform Init
+#        id: init
+#        run: terraform init
+#
+#      - name: Terraform Validate
+#        id: validate
+#        uses: hashicorp/terraform-github-actions/validate@v0.3.7
+#
+#      - name: Terraform Plan
+#        id: plan
+#        run: terraform plan -no-color
+#        if: github.event_name == 'pull_request'
+#        continue-on-error: true
+#
+#      - uses: actions/github-script@v6
+#        if: github.event_name == 'pull_request'
+#        env:
+#          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#        with:
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+#          script: |
+#            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+#            <details><summary>Validation Output</summary>
+#
+#            \`\`\`\n
+#            ${{ steps.validate.outputs.stdout }}
+#            \`\`\`
+#
+#            </details>
+#
+#            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#
+#            <details><summary>Show Plan</summary>
+#
+#            \`\`\`\n
+#            ${process.env.PLAN}
+#            \`\`\`
+#
+#            </details>
+#
+#            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#
+#            github.rest.issues.createComment({
+#              issue_number: context.issue.number,
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#              body: output
+#            })
+#
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        run: exit 1
+#
+#      - name: Terraform Apply
+#        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#        run: terraform apply -auto-approve -input=false
+#        env:
+#          TF_VAR_DJANGO_SECRET_KEY:  ${{ secrets.DJANGO_SECRET_KEY }}
+#          TF_VAR_DEBUG:  ${{ vars.DEBUG_MODE }}
+#          TF_VAR_DATABASE_NAME: ${{secrets.POSTGRES_DB}}
+#          TF_VAR_DATABASE_USER: ${{secrets.POSTGRES_USER}}
+#          TF_VAR_DATABASE_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
+#          TF_VAR_AFRICASTALKING_API_KEY:  ${{ secrets.AFRICASTALKING_API_KEY }}
+#          TF_VAR_AFRICASTALKING_USERNAME:  ${{ secrets.AFRICASTALKING_USERNAME }}
+#          TF_VAR_AFRICASTALKING_SENDER:  ${{ secrets.AFRICASTALKING_SENDER_ID }}
 
 #  build-and-push:
 #    name: Deploy
